/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"


#define MAIN_GPIOA						GPIOA
#define MAIN_UART1_TX_PIN				GPIO_PIN_9
#define MAIN_UART1_RX_PIN				GPIO_PIN_10
#define MAIN_UART_BAUD_RATE 			115200
#define MAIN_UART_STOP_BIT 				UART_STOPBITS_1
#define MAIN_UART_START_BIT 			1
#define MAIN_USART1_INSTANCE 			USART1
#define MAIN_USART2_INSTANCE 			USART2
#define MAIN_UART_WORD_LENGTH 			UART_WORDLENGTH_8B
#define MAIN_UART_PARITY 				UART_PARITY_NONE
#define MAIN_UART_MODE					UART_MODE_TX_RX
#define MAIN_UART_HARDWARE_CONTROL		UART_HWCONTROL_NONE
#define MAIN_UART_OVER_SAMPLING			UART_OVERSAMPLING_16
#define MAIN_BUFFER_SIZE				20
#define MAIN_UART_TIMEOUT				20
#define MAIN_DELAY_TIME_MS				500	

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif

// Global variables
//made this global to test printf
UART_HandleTypeDef UART1_handle_init = {0};
UART_HandleTypeDef UART2_handle_init = {0};

uint32_t rx_counter_uart1 = 0;
uint32_t tx_counter_uart1 = 0;
uint32_t rx_counter_uart2 = 0;
uint32_t tx_counter_uart2 = 0;

uint8_t tx_buffer_uart1[MAIN_BUFFER_SIZE] = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200};
uint8_t rx_buffer_uart1[MAIN_BUFFER_SIZE] = {0};

uint8_t tx_buffer_uart2[MAIN_BUFFER_SIZE] = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200};
uint8_t rx_buffer_uart2[MAIN_BUFFER_SIZE] = {0};

// Function prototypes
static void s_main_usart1_init(GPIO_InitTypeDef* GPIO_init);
static void s_main_usart2_init(GPIO_InitTypeDef* GPIO_init);

int main(void)
{

	GPIO_InitTypeDef GPIO_init_uart1 = {0};
	GPIO_InitTypeDef GPIO_init_uart2 = {0};
	//UART_HandleTypeDef UART2_handle_init = {0};
	//const uint8_t transmit_data[MAIN_BUFFER_SIZE] = "HELLO can you";

	HAL_Init();
	s_main_usart1_init(&GPIO_init_uart1);
	s_main_usart2_init(&GPIO_init_uart2);


	HAL_UART_Transmit_IT(&UART1_handle_init, tx_buffer_uart1, MAIN_BUFFER_SIZE);
	HAL_UART_Receive_IT(&UART1_handle_init, rx_buffer_uart1, MAIN_BUFFER_SIZE);
	
	HAL_UART_Transmit_IT(&UART2_handle_init, tx_buffer_uart2, MAIN_BUFFER_SIZE);
	//HAL_UART_Receive_IT(&UART2_handle_init, rx_buffer_uart2, MAIN_BUFFER_SIZE);
	
	
	for(;;)
	{
		//printf("Printf is being used/n");
	}
}

void s_main_usart1_init(GPIO_InitTypeDef * GPIO_init)
{
	//__HAL_RCC_GPIOA_IS_CLK_ENABLED();
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_USART1_CLK_ENABLE();

	GPIO_init->Mode = GPIO_MODE_AF_PP;
	GPIO_init->Pin = GPIO_PIN_9 | GPIO_PIN_10;
	GPIO_init->Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	GPIO_init->Pull = GPIO_NOPULL;
	GPIO_init->Alternate = GPIO_AF7_USART1;

	HAL_GPIO_Init(MAIN_GPIOA, GPIO_init);
	
	UART1_handle_init.Instance = MAIN_USART1_INSTANCE;
	UART1_handle_init.Init.BaudRate = MAIN_UART_BAUD_RATE;
	UART1_handle_init.Init.StopBits = MAIN_UART_STOP_BIT;
	UART1_handle_init.Init.WordLength = MAIN_UART_WORD_LENGTH;
	UART1_handle_init.Init.Parity = MAIN_UART_PARITY;
	UART1_handle_init.Init.Mode = MAIN_UART_MODE;
	UART1_handle_init.Init.HwFlowCtl = MAIN_UART_HARDWARE_CONTROL;
	UART1_handle_init.Init.OverSampling = MAIN_UART_OVER_SAMPLING;

	HAL_UART_Init(&UART1_handle_init);

	HAL_NVIC_SetPriority(USART1_IRQn, 0, 0);
	HAL_NVIC_EnableIRQ(USART1_IRQn);


}

void s_main_usart2_init(GPIO_InitTypeDef * GPIO_init)
{
	//__HAL_RCC_GPIOA_IS_CLK_ENABLED();
	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_USART2_CLK_ENABLE();

	GPIO_init->Mode = GPIO_MODE_AF_PP;
	GPIO_init->Pin = GPIO_PIN_2 | GPIO_PIN_3;
	GPIO_init->Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	GPIO_init->Pull = GPIO_NOPULL;
	GPIO_init->Alternate = GPIO_AF7_USART2;

	HAL_GPIO_Init(MAIN_GPIOA, GPIO_init);
	
	UART2_handle_init.Instance = MAIN_USART2_INSTANCE;
	UART2_handle_init.Init.BaudRate = MAIN_UART_BAUD_RATE;
	UART2_handle_init.Init.StopBits = MAIN_UART_STOP_BIT;
	UART2_handle_init.Init.WordLength = MAIN_UART_WORD_LENGTH;
	UART2_handle_init.Init.Parity = MAIN_UART_PARITY;
	UART2_handle_init.Init.Mode = MAIN_UART_MODE;
	UART2_handle_init.Init.HwFlowCtl = MAIN_UART_HARDWARE_CONTROL;
	UART2_handle_init.Init.OverSampling = MAIN_UART_OVER_SAMPLING;

	HAL_UART_Init(&UART2_handle_init);

	HAL_NVIC_SetPriority(USART2_IRQn, 0, 0);
	HAL_NVIC_EnableIRQ(USART2_IRQn);


}


//handler called for each byte received or transmitted when using interrupt mode. 
//The callback is called in the context of the main loop, not in the context of the interrupt handler. 
//This means that the callback will be executed after the interrupt handler has finished processing the interrupt and returned to the main loop. 
//This allows for more efficient handling of UART events without blocking the main loop with lengthy processing in the interrupt context.
void USART1_IRQHandler(void)
{
	HAL_UART_IRQHandler(&UART1_handle_init);
}

void USART2_IRQHandler(void)
{
	HAL_UART_IRQHandler(&UART2_handle_init);
}



void HAL_UART_TxCpltCallback(UART_HandleTypeDef* huart)
{
	// // Transmission complete callback
	// // You can add your code here to handle post-transmission tasks
	// tx_counter++;

	// //method1
	// if(huart == &UART1_handle_init)
	// {
	// 	tx_counter_uart1++;
	// }
	// else if(huart == &UART2_handle_init)
	// {
	// 	tx_counter_uart2++;
	// }
	//method2
	if(huart->Instance == MAIN_USART1_INSTANCE)
	{
		tx_counter_uart1++;
	}
	else if(huart->Instance == MAIN_USART2_INSTANCE)
	{
		tx_counter_uart2++;
	}
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef* huart)
{
	// // Reception complete callback
	// // You can add your code here to handle post-reception tasks
	// rx_counter++;

	// if(huart == &UART1_handle_init)
	// {
	// 	rx_counter_uart1++;
	// }
	// else if(huart == &UART2_handle_init)
	// {
	// 	rx_counter_uart2++;
	// }
	if(huart->Instance == MAIN_USART1_INSTANCE)
	{
		rx_counter_uart1++;
	}
	else if(huart->Instance == MAIN_USART2_INSTANCE)
	{
		rx_counter_uart2++;
	}
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}

int __io_putchar(int ch)
{
	//HAL_UART_Transmit(&UART1_handle_init, (uint8_t *)&ch, 1, MAIN_UART_TIMEOUT);
	//HAL_Delay(MAIN_DELAY_TIME_MS);
}


















