/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"


#define BTN_PORT		GPIOC
#define BTN_PIN			GPIO_PIN_13
#define LED_PORT		GPIOA
#define LED_PIN			GPIO_PIN_5


//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif


static void s_init_led(GPIO_InitTypeDef * t_led_port_config);
static void s_init_push_button(GPIO_InitTypeDef * t_button_port_config);


int main(void)
{
	GPIO_InitTypeDef gpio_port_init = {0};
	uint8_t button_pressed = 0;

	HAL_Init();
	s_init_led(&gpio_port_init);
	s_init_push_button(&gpio_port_init);


	for(;;)
	{
		button_pressed = HAL_GPIO_ReadPin(BTN_PORT, BTN_PIN);
		HAL_GPIO_WritePin(LED_PORT, BTN_PIN, button_pressed);

	}
}

void s_init_led(GPIO_InitTypeDef * t_led_port_config)
{
	__HAL_RCC_GPIOA_CLK_ENABLE();
	t_led_port_config->Mode = GPIO_MODE_OUTPUT_PP;
	t_led_port_config->Pin = LED_PIN;
	t_led_port_config->Pull = GPIO_NOPULL;
	t_led_port_config->Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(LED_PORT, t_led_port_config);
}

static void s_init_push_button(GPIO_InitTypeDef * t_button_port_config)
{
	__HAL_RCC_GPIOC_CLK_ENABLE();
	t_button_port_config->Mode = GPIO_MODE_INPUT;
	t_button_port_config->Pin = BTN_PIN;
	t_button_port_config->Pull = GPIO_NOPULL;
	t_button_port_config->Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(BTN_PORT, t_button_port_config);
}



















