/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "uart.h"
#include "adc.h"

UART_HandleTypeDef UART2_handle_init = {0};
ADC_HandleTypeDef hadc1;

int main(void)
{

	GPIO_InitTypeDef GPIO_init = {0};
	uint32_t read_adc1_value = 0;
	//UART_HandleTypeDef UART2_handle_init = {0};
	//const uint8_t transmit_data[MAIN_BUFFER_SIZE] = "HELLO can you";

	HAL_Init();
	//usart_init(&GPIO_init, &UART2_handle_init);
	usart_init(&GPIO_init, &UART2_handle_init);
	adc_pa0_single_conv_init();
	//adc_init_start();
	

	for(;;)
	{
		HAL_ADC_Start(&hadc1);
		HAL_ADC_PollForConversion(&hadc1, 1);
		read_adc1_value = pa0_ac_read();
		printf("Read ADC value: %lu", read_adc1_value);
		HAL_Delay(10);

	}
}



void SysTick_Handler(void)
{
	HAL_IncTick();
}



















