/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "uart.h"
#include "adc.h"

#define MAIN_BUFFER_SIZE				20
#define MAIN_UART_TIMEOUT				100

void spi1_init(void);

UART_HandleTypeDef UART2_handle_init = {0};
ADC_HandleTypeDef hadc1 = {0};
SPI_HandleTypeDef SPI1_handle_init = {0};



uint8_t tx_data_buffer[MAIN_BUFFER_SIZE] = {10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200};
uint8_t rx_data_buffer[MAIN_BUFFER_SIZE] = {0};


int main(void)
{
	HAL_Init();
	spi1_init();

	HAL_SPI_TransmitReceive(&SPI1_handle_init, tx_data_buffer, rx_data_buffer, MAIN_BUFFER_SIZE, MAIN_UART_TIMEOUT);


	while(1)
	{

	}
}



void SysTick_Handler(void)
{
	HAL_IncTick();
}




void spi1_init(void)
{
	GPIO_InitTypeDef GPIO_init = {0};

	__HAL_RCC_GPIOA_CLK_ENABLE();
	__HAL_RCC_SPI1_CLK_ENABLE();

	//PA5 - SCK
	//PA6 - MISO
	//PA7 - MOSI 

	GPIO_init.Mode = GPIO_MODE_AF_PP;
	GPIO_init.Pin = GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7;
	GPIO_init.Speed = GPIO_SPEED_FREQ_VERY_HIGH;
	GPIO_init.Pull = GPIO_NOPULL;
	GPIO_init.Alternate = GPIO_AF5_SPI1;
	HAL_GPIO_Init(GPIOA, &GPIO_init);


	SPI1_handle_init.Instance = SPI1;
	SPI1_handle_init.Init.Mode = SPI_MODE_MASTER;
	SPI1_handle_init.Init.Direction = SPI_DIRECTION_2LINES;
	SPI1_handle_init.Init.DataSize = SPI_DATASIZE_8BIT;
	SPI1_handle_init.Init.CLKPolarity = SPI_POLARITY_LOW;
	SPI1_handle_init.Init.CLKPhase = SPI_PHASE_1EDGE;
	SPI1_handle_init.Init.NSS = SPI_NSS_SOFT;
	SPI1_handle_init.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_16;
	SPI1_handle_init.Init.FirstBit = SPI_FIRSTBIT_MSB;
	SPI1_handle_init.Init.TIMode = SPI_TIMODE_DISABLED;
	SPI1_handle_init.Init.CRCCalculation = SPI_CRCCALCULATION_DISABLE;
	//SPI1_handle_init.Init.CRCPolynomial = 10;
	HAL_SPI_Init(&SPI1_handle_init);


}














