/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "uart.h"
#include "adc.h"
#include "tim.h"
#include "led.h"



UART_HandleTypeDef UART2_handle_init;
GPIO_InitTypeDef GPIO_init;

int main(void)
{
	HAL_Init();
	//gpio_pa5_led_init();
	timx_base_init();
	usart_init(&GPIO_init, &UART2_handle_init);	
	
	while (1)
	{
		;
	}
	

}



void SysTick_Handler(void)
{
	HAL_IncTick();
}

















