/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "uart.h"
#include "adc.h"

#define BTN_PORT		GPIOC
#define BTN_PIN			GPIO_PIN_13
#define LED_PORT		GPIOA
#define LED_PIN			GPIO_PIN_5

void gpio_pc13_interrupt_callback_init(void);

int main(void)
{
	HAL_Init();
	gpio_pc13_interrupt_callback_init();
	//usart_init();

	while (1)
	{
		
	}
	

}



void SysTick_Handler(void)
{
	HAL_IncTick();
}

void gpio_pc13_interrupt_callback_init(void)
{
	GPIO_InitTypeDef gpio_port_init = {0};
	
	__HAL_RCC_GPIOC_CLK_ENABLE();
	gpio_port_init.Pin = BTN_PIN;
	gpio_port_init.Mode = GPIO_MODE_IT_RISING;
	gpio_port_init.Pull = GPIO_NOPULL;
	gpio_port_init.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(BTN_PORT, &gpio_port_init);



	__HAL_RCC_GPIOA_CLK_ENABLE();
	gpio_port_init.Pin = LED_PIN;
	gpio_port_init.Mode = GPIO_MODE_OUTPUT_PP;
	gpio_port_init.Pull = GPIO_NOPULL;
	gpio_port_init.Speed = GPIO_SPEED_FREQ_LOW;
	HAL_GPIO_Init(LED_PORT, &gpio_port_init);

	//HAL_GPIO_TogglePin(GPIOC, GPIO_PIN_12);

	//configure and enable EXTI line 15 to 10 interrupt in NVIC
	//since button is connected to PC13 use EXTI15_10_IRQn
	HAL_NVIC_SetPriority(EXTI15_10_IRQn, 0, 0);
	HAL_NVIC_EnableIRQ(EXTI15_10_IRQn);
}

void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
	HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
	printf("Button Pressed! Toggle the LED.\n");
}

//EXTI15_10_IRQHandler name is in the vector table in startup_stm32f4xx.s
void EXTI15_10_IRQHandler(void)
{

	HAL_GPIO_EXTI_IRQHandler(BTN_PIN);

	//check if the interrupt is generated from pin 13
	// if(__HAL_GPIO_EXTI_GET_IT(BTN_PIN) != RESET)
	// {
	// 	//clear the pending interrupt flag for pin 13
	// 	__HAL_GPIO_EXTI_CLEAR_IT(BTN_PIN);
		
	// 	//toggle the LED pin
	// 	HAL_GPIO_TogglePin(LED_PORT, LED_PIN);
	// }
}

















