/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx_hal.h"
#include "uart.h"
#include "adc.h"
#include "i2c.h"


void int_to_string(int16_t num, char *str);


UART_HandleTypeDef UART2_handle_init = {0};
uint8_t datarec[6] = {0}; 						//to store x, y, z axis data from adxl345. Higher byte is stored in odd index and lower byte is stored in even index. 
						  						//For example, x-axis higher byte is stored in datarec[1] and lower byte is stored in datarec[0].

//made global for liveepression in debugger prevents optimization.
int16_t x_axis = 0, y_axis = 0, z_axis = 0;
float x_axis_g = 0.0, y_axis_g = 0.0, z_axis_g = 0.0;



int main(void)
{

	GPIO_InitTypeDef GPIO_init = {0};
	char value_str[10] = {0};


	//UART_HandleTypeDef UART2_handle_init = {0};
	//const uint8_t transmit_data[MAIN_BUFFER_SIZE] = "HELLO can you";

	HAL_Init();
	usart_init(&GPIO_init, &UART2_handle_init);
	i2c_init();
	adxl345_init();
	ssd1306_init();
	ssd1306_clear();

	ssd1306_setpos(0, 0);
	ssd1306_set_string((int8_t *)"X_AXIS: ");
	ssd1306_setpos(0, 1);
	ssd1306_set_string((int8_t *)"Y_AXIS: ");
	ssd1306_setpos(0, 2);
	ssd1306_set_string((int8_t *)"Z_AXIS: ");

	while(1)
	{
		adxl345_read_values(DATA_START_ADDR);
		x_axis = (int16_t)(datarec[1] << 8 | datarec[0]);
		y_axis = (int16_t)(datarec[3] << 8 | datarec[2]);
		z_axis = (int16_t)(datarec[5] << 8 | datarec[4]);

		x_axis_g = x_axis * FOUR_G_SCALE_FACTOR;
		y_axis_g = y_axis * FOUR_G_SCALE_FACTOR;
		z_axis_g = z_axis * FOUR_G_SCALE_FACTOR;
		

		HAL_Delay(500);

		int_to_string(x_axis, value_str);
		ssd1306_setpos(73, 0);
		ssd1306_set_string((int8_t *)value_str);

		int_to_string(y_axis, value_str);
		ssd1306_setpos(73, 1);
		ssd1306_set_string((int8_t *)value_str);

		int_to_string(z_axis, value_str);
		ssd1306_setpos(73, 2);
		ssd1306_set_string((int8_t *)value_str);
		
	}
}

void int_to_string(int16_t num, char *str)
{
	char temp[10];
	int i = 0, j = 0;
	if(num < 0)
	{
		str[j++] = '-';
		num = -num;
	}
	while(num > 0)
	{
		temp[i++] = (num % 10) + '0';
		num /= 10;
	}
	while(i > 0)
	{
		str[j++] = temp[--i];
	}
	str[j] = '\0';
}


void SysTick_Handler(void)
{
	HAL_IncTick();
}



















