/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// #include "stm32f4xx_hal.h"
#include "uart.h"
#include "adc.h"

UART_HandleTypeDef UART2_handle_init = {0};
ADC_HandleTypeDef hadc1;
DMA_HandleTypeDef hdma_adc1;
uint32_t read_adc_sensor_value = 0;
uint32_t read_adc_sensor_value_array[10] = {0};
uint32_t multi_adc_value_array[2] = {0};

int main(void)
{

	GPIO_InitTypeDef GPIO_init = {0};

	//UART_HandleTypeDef UART2_handle_init = {0};
	//const uint8_t transmit_data[MAIN_BUFFER_SIZE] = "HELLO can you";

	HAL_Init();
	usart_init(&GPIO_init, &UART2_handle_init);
	// adc_pa0_interrupt_init();
	

	// //1st method to start adc conversion
	// HAL_ADC_Start_IT(&hadc1);
	adc_pa0_pa4_dma_init();
	HAL_ADC_Start_DMA(&hadc1, (uint32_t *)multi_adc_value_array, 2);


	for(;;)
	{
		//printf("Read ADC value: %lu\r\n", read_adc_sensor_value);
		printf("Read ADC sensor value 1: %ld\r\n", multi_adc_value_array[0]);
		printf("Read ADC sensor value 2: %ld\r\n", multi_adc_value_array[1]);
		//HAL_Delay(10);

	}
}

void HAL_ADC_ConvCpltCallback(ADC_HandleTypeDef *hadc)
{
	//this function is called when adc conversion is complete
	read_adc_sensor_value = pa0_adc_read();
	HAL_ADC_Start_IT(&hadc1);
	printf("ADC Interrupt Value: %lu\r\n", read_adc_sensor_value);
	
}

void SysTick_Handler(void)
{
	HAL_IncTick();
}



















